import = ["/Users/jaime/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "debian.exe"

[window]
decorations = "buttonless"
opacity = 0.95

[window.padding]
x = 5
y = 5
