local wezterm = require("wezterm")
return {
  audible_bell = "Disabled",
  color_scheme = "Catppuccin Mocha", -- or Macchiato, Frappe, Latte
  default_prog = { "powershell.exe", "-NoLogo" },
  -- Pad the window content:
  window_padding = {
    left = 3,
    right = 3,
    top = 3,
    bottom = 3,
  },
  -- window_background_opacity = 0.9,
  inactive_pane_hsb = {
    hue = 1.0,
    saturation = 0.9,
    brightness = 0.7,
  },
  -- How many lines of scrollback you want to retain per tab
  scrollback_lines = 3500,
  font = wezterm.font("JetBrainsMono Nerd Font"),
  font_size = 12.0,
  leader = { key = "a", mods = "CTRL" },
  hide_tab_bar_if_only_one_tab = true,
  keys = {
    { key = "a", mods = "LEADER|CTRL", action = wezterm.action({ SendString = "\x01" }) },
    { key = "-", mods = "LEADER", action = wezterm.action({ SplitVertical = { domain = "CurrentPaneDomain" } }) },
    {
      key = "\\",
      mods = "LEADER",
      action = wezterm.action({ SplitHorizontal = { domain = "CurrentPaneDomain" } }),
    },
    { key = "m", mods = "SHIFT|CTRL", action = wezterm.action.ToggleFullScreen },
    { key = "s", mods = "LEADER", action = wezterm.action({ SplitVertical = { domain = "CurrentPaneDomain" } }) },
    { key = "v", mods = "LEADER", action = wezterm.action({ SplitHorizontal = { domain = "CurrentPaneDomain" } }) },
    { key = "o", mods = "LEADER", action = "TogglePaneZoomState" },
    { key = "z", mods = "LEADER", action = "TogglePaneZoomState" },
    { key = "c", mods = "LEADER", action = wezterm.action({ SpawnTab = "CurrentPaneDomain" }) },
    { key = "h", mods = "SHIFT|CTRL", action = wezterm.action({ ActivatePaneDirection = "Left" }) },
    { key = "j", mods = "SHIFT|CTRL", action = wezterm.action({ ActivatePaneDirection = "Down" }) },
    { key = "k", mods = "SHIFT|CTRL", action = wezterm.action({ ActivatePaneDirection = "Up" }) },
    { key = "l", mods = "SHIFT|CTRL", action = wezterm.action({ ActivatePaneDirection = "Right" }) },
    { key = "h", mods = "LEADER", action = wezterm.action({ AdjustPaneSize = { "Left", 5 } }) },
    { key = "j", mods = "LEADER", action = wezterm.action({ AdjustPaneSize = { "Down", 5 } }) },
    { key = "k", mods = "LEADER", action = wezterm.action({ AdjustPaneSize = { "Up", 5 } }) },
    { key = "l", mods = "LEADER", action = wezterm.action({ AdjustPaneSize = { "Right", 5 } }) },
    { key = "1", mods = "LEADER", action = wezterm.action({ ActivateTab = 0 }) },
    { key = "2", mods = "LEADER", action = wezterm.action({ ActivateTab = 1 }) },
    { key = "3", mods = "LEADER", action = wezterm.action({ ActivateTab = 2 }) },
    { key = "4", mods = "LEADER", action = wezterm.action({ ActivateTab = 3 }) },
    { key = "5", mods = "LEADER", action = wezterm.action({ ActivateTab = 4 }) },
    { key = "6", mods = "LEADER", action = wezterm.action({ ActivateTab = 5 }) },
    { key = "7", mods = "LEADER", action = wezterm.action({ ActivateTab = 6 }) },
    { key = "8", mods = "LEADER", action = wezterm.action({ ActivateTab = 7 }) },
    { key = "9", mods = "LEADER", action = wezterm.action({ ActivateTab = 8 }) },
    { key = "x", mods = "LEADER", action = wezterm.action({ CloseCurrentPane = { confirm = true } }) },
  },
}
